<!DOCTYPE html>
<%@page import="com.xlx.commonn.CommonAppConstants"%>
<%@page import="com.xlx.treds.instrument.bean.CersaiFileBean"%>
<%@page import="com.xlx.commonn.BeanMetaFactory"%>
<%
Boolean lNew = (Boolean)request.getAttribute(CommonAppConstants.PARAM_NEW);
boolean lNewBool = (lNew != null) && lNew.booleanValue();
String lModify = (String)request.getAttribute(CommonAppConstants.PARAM_MODIFY);
%>
<html>
	<head>
		<title>CersaiFiles : The list of CERSAI files generated. It records the date of generation by the financier, and the instruments included in it.</title>
        <%@include file="includes1.jsp" %>
        <link href="../css/bootstrap-datetimepicker.css" rel="stylesheet">
		<link href="../css/datatables.css" rel="stylesheet"/>
		<!-- <link href="../css/bootstrap-duallistbox.css" rel="stylesheet"/> -->
	</head>
	<body class="page-body">
	<jsp:include page="header1.jsp">
		<jsp:param name="title" value="CersaiFiles : The list of CERSAI files generated. It records the date of generation by the financier, and the instruments included in it." />
		<jsp:param name="desc" value="" />
	</jsp:include>

	<div class="content" id="contCersaiFile">		
		<div id="frmSearch">
			<div class="page-title">
				<div class="title-env">
					<h1 class="title">CERSAI Files</h1>
				</div>
			</div>
			<!-- <header>CersaiFiles : The list of CERSAI files generated. It records the date of generation by the financier, and the instruments included in it.</header> -->

			<div class="xform tab-pane panel panel-default no-margin collapse in" id=divFilter>
			<fieldset class="form-horizontal">
				<div class="row">
					<div class="col-sm-2"><section><label for="id" class="label">Id:</label></section></div>
					<div class="col-sm-4">
						<section class="input">
						<input type="text" id="id" placeholder="Id">
						<b class="tooltip tooltip-top-right"></b></section>
					</div>
					<div class="col-sm-2"><section><label for="date" class="label">Date:</label></section></div>
					<div class="col-sm-4">
						<section class="input">
						<i class="icon-append fa fa-clock-o"></i>
						<input type="text" id="date" placeholder="Date" data-role="datetimepicker">
						<b class="tooltip tooltip-top-right"></b></section>
					</div>
				</div>
				<div class="row">
					<div class="col-sm-12">
						<div class="btn-groupX pull-right">
							<button type="button" class="btn btn-enter btn-info btn-lg" id=btnSearch><span class="fa fa-search"></span> Search</button>
							<button type="button" class="btn btn-info-inverse btn-lg" id=btnFilterClr>Clear Filter</button>
						</div>
					</div>
				</div>
			</fieldset>
			</div>
			<div class="filter-block clearfix">
				<div class="">
					<a class="left_links" href="javascript:;" data-toggle="collapse" data-target="#divFilter">Filter</a>
					<a href="javascript:;" class="right_links" id=btnDownloadFile style=''><span class="fa fa-download"></span> Download File</a>
					<a href="javascript:;" class="right_links" id=btnDownloadCSV style=''><span class="fa fa-download"></span> Download CSV</a>
					<a href="javascript:;" class="right_links cersaifile-save" id=btnGenerateFile style=''><span class="fa fa-plus"></span> Generate File</a>
					<a></a>
				</div>
			</div>
			
			<div class="tab-pane panel panel-default">
			<fieldset>
				<div class="row">
					<div class="col-sm-12">

						<table class="table table-bordered table-condensed" id="tblData" width="1000px" data-scroll-y="300px">
							<thead><tr>
								<th data-width="50px" data-name="id">Id</th>
								<th data-width="100px" data-name="date">Date</th>
								<th data-width="300px" data-name="fileName">File Name</th>
								<th data-width="50px" data-name="serialNumber">Serial No</th>
								<th data-width="70px" data-name="recordCount">Record Count</th>
								<th data-width="300px" data-name="generatedByLoginId">Generated By</th>
								<th data-width="200px" data-name="generatedTime">Generated Time</th>
								<th data-width="0px" data-name="generatedByAuId"  data-sel-exclude="true" data-visible="false">Generated By</th>
							</tr></thead>
						</table>
					</div>
				</div>
			</fieldset>
			</div>
		</div>
		<!-- frmSearch -->
		
		<!-- frmMain -->
		<div style="display:none" id="frmMain">
			<!-- <header>CersaiFiles : The list of CERSAI files generated. It records the date of generation by the financier, and the instruments included in it.</header> -->
			<div class="page-title">
				<div class="title-env">
					<h1 class="title">List of CERSAI files generated.</h1>
				</div>
			</div>

    		<div class="xform box">
			<fieldset>
				<div class="row">
					<div class="col-sm-2"><section><label for="id" class="label">Id:</label></section></div>
					<div class="col-sm-4">
						<section class="input">
						<input type="text" id="id" placeholder="Id">
						<b class="tooltip tooltip-top-right"></b></section>
						<section class="view"></section>
					</div>
					<div class="col-sm-2"><section><label for="date" class="label">Date:</label></section></div>
					<div class="col-sm-4">
						<section class="input">
						<i class="icon-append fa fa-clock-o"></i>
						<input type="text" id="date" placeholder="Date" data-role="datetimepicker">
						<b class="tooltip tooltip-top-right"></b></section>
						<section class="view"></section>
					</div>
				</div>
				<div class="row">
					<div class="col-sm-2"><section><label for="financier" class="label">Financier:</label></section></div>
					<div class="col-sm-4">
						<section class="select">
						<select id="financier"><option value="">Select Financier</option></select>
						<b class="tooltip tooltip-top-right"></b><i></i></section>
						<section class="view"></section>
					</div>
					<div class="col-sm-2"><section><label for="fileName" class="label">File Name:</label></section></div>
					<div class="col-sm-4">
						<section class="input">
						<input type="text" id="fileName" placeholder="File Name">
						<b class="tooltip tooltip-top-right"></b></section>
						<section class="view"></section>
					</div>
				</div>
				<div class="row">
					<div class="col-sm-2"><section><label for="recordCount" class="label">No of Records:</label></section></div>
					<div class="col-sm-4">
						<section class="input">
						<input type="text" id="recordCount" placeholder="No of Records">
						<b class="tooltip tooltip-top-right"></b></section>
						<section class="view"></section>
					</div>
					<div class="col-sm-2"><section><label for="generatedByAuId" class="label">Generated By:</label></section></div>
					<div class="col-sm-4">
						<section class="input">
						<input type="text" id="generatedByAuId" placeholder="Generated By">
						<b class="tooltip tooltip-top-right"></b></section>
						<section class="view"></section>
					</div>
				</div>
				<div class="row">
					<div class="col-sm-2"><section><label for="generatedTime" class="label">Generated Time:</label></section></div>
					<div class="col-sm-4">
						<section class="input">
						<i class="icon-append fa fa-clock-o"></i>
						<input type="text" id="generatedTime" placeholder="Generated Time" data-role="datetimepicker">
						<b class="tooltip tooltip-top-right"></b></section>
						<section class="view"></section>
					</div>
				</div>
			</fieldset>
    		<div class="box-footer">
				<div class="row">
					<div class="col-sm-12">
						<div class="btn-groupX pull-right">
							<button type="button" class="btn btn-info-inverse btn-lg btn-close" id=btnClose><span class="fa fa-close"></span> Close</button>
						</div>
					</div>
				</div>
    		</div>
			</div>
		</div>
	</div>
	
	<div class="modal fade" id=mdlGenerate tabindex=-1><div class="modal-dialog modal-md"><div class="modal-content">
		<div class="modal-header"><span>Generate Payment File</span><button type="button" class="btn btn-sm pull-right" data-dismiss="modal"><i class="fa fa-close"></i></button></div>
		<div class="modal-body modal-no-padding">
		<div class="xform" id="mod-frmMain">
			<fieldset>
				<div class="row">
					<div class="col-sm-4"><section><label for="date" class="label">Date:</label></section></div>
					<div class="col-sm-8">
						<section class="input">
						<i class="icon-append fa fa-clock-o"></i>
						<input type="text" id="date" placeholder="Date" data-role="datetimepicker">
						<b class="tooltip tooltip-top-right"></b></section>
						<section class="view"></section>
					</div>
				</div>
	    		<div class="box-footer">
					<div class="row">
						<div class="col-sm-12">
							<div class="btn-groupX pull-right">
								<button type="button" class="btn btn-info btn-lg btn-enter" id=btnGen> Generate</button>
								<button type="button" class="btn btn-info-inverse btn-lg btn-close" id=btnClose><span class="fa fa-close"></span> Close</button>
							</div>
						</div>
					</div>
				</div>
			</fieldset>
		</div>
		</div></div></div></div>

   	<%@include file="footer1.jsp" %>
	<script src="../js/bootstrap-datetimepicker.js"></script>
   	<script src="../js/datatables.js"></script>
	<script type="text/javascript">
		var crudCersaiFile$ = null;
		$(document).ready(function() {
			var lFormConfig = <%=BeanMetaFactory.getInstance().getBeanMeta(CersaiFileBean.class).getJsonConfig()%>;
			var lConfig = {
					resource: "cersaifile",
					autoRefresh: true,
<%
if (lNewBool) {
%>					new: true,
<%
} else if (lModify != null) {
%>					modify: <%=lModify%>,
<%
}
%>			};
			lConfig = $.extend(lConfig, lFormConfig);
			crudCersaiFile$ = $('#contCersaiFile').xcrudwrapper(lConfig);
			crudCersaiFile = crudCersaiFile$.data('xcrudwrapper');
			$('#btnGenerateFile').on('click', function() {
				$('#mdlGenerate').modal('show');
			});
			var lModifyConfig = {
					"fields": [
						{
							"name":"date",
							"label":"Date",
							"dataType":"DATE",
							"notNull": true
						}
					]
				};
		modForm$ = $('#mod-frmMain').xform(lModifyConfig);
		modForm = modForm$.data('xform');
		
		$('#btnGen').on('click', function(){
			var lDate = modForm.getField('date').getValue();
			$.ajax( {
	            url: 'cersaifile/checkGeneration/'+lDate,
	            type: "GET",
	            success: function( pObj, pStatus, pXhr) {
	            	$('#mdlGenerate').modal('hide');
	            	if(pObj!=null){
	            		if(pObj[0].newCount == 0){
		            		oldAlert(pObj[0].message);
	            		}else{
	            			confirm(pObj[0].message + ' Do you want to generate?','Confirmation','Yes',function(pYes) {
	            				if (pYes){
	            					$.ajax( {
	            			            url: 'cersaifile/generate/'+lDate,
	            			            type: "GET",
	            			            success: function( pObj, pStatus, pXhr) {
	            			            	var pMessage = '';
	            			            	if(pObj!=null){
	            			            		alert(pObj[0].message);
	            			            		crudCersaiFile.showSearchForm();
	            			            	}
	            			            },
	            			        	error: errorHandler,
	            			        	complete: function() {
	            			        	}
	            			        });
	            				}
	            			});
	            			return;
	            		}
	            	}
	            },
	        	error: errorHandler,
	        	complete: function() {
	        	}
	        });
		});
		
		$('#btnDownloadFile').on('click', function(){
			var lSelected = crudCersaiFile.getSelectedRow();
			if ((lSelected==null)||(lSelected.length==0)) {
				alert("Please select a row");
				return;
			}
			var lData = {"id":lSelected.data().id};
			if (lData!=null){
				downloadFile('cersaifile/download',null,JSON.stringify(lData));
			}
		});
		
		$('#btnDownloadCSV').on('click', function(){
			var lSelected = crudCersaiFile.getSelectedRow();
			if ((lSelected==null)||(lSelected.length==0)) {
				alert("Please select a row");
				return;
			}
			var lData = {"id":lSelected.data().id, "csv":true};
			if (lData!=null){
				downloadFile('cersaifile/download',null,JSON.stringify(lData));
			}
		});

		});
		
	</script>


</body>
</html>