<!DOCTYPE html>
<%@page import="com.xlx.commonn.CommonAppConstants"%>
<%@page import="com.xlx.commonn.BeanMetaFactory"%>
<%
Boolean lNew = (Boolean)request.getAttribute(CommonAppConstants.PARAM_NEW);
boolean lNewBool = (lNew != null) && lNew.booleanValue();
String lModify = (String)request.getAttribute(CommonAppConstants.PARAM_MODIFY);
%>
<html lang="en">
  <head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	
	<title>Obligation File Transfers</title>
    <link href="../css/bootstrap.min.css" rel="stylesheet">
    <link href="../css/font-awesome.min.css" rel="stylesheet">
	<link href="../css/global.css" rel="stylesheet">

	<!-- <link href="../css/bootstrap-datetimepicker.css" rel="stylesheet"> -->
	<!-- <link href="../css/bootstrap-duallistbox.css" rel="stylesheet"/> -->
	<!-- <link href="../css/bootstrap-multiselect.css" rel="stylesheet"/> -->
	<!-- <link href="../css/select2.css" rel="stylesheet"/> -->
	<!-- <link href="../css/datatables.css" rel="stylesheet"/> -->

</head>
<body>
<%@ include file="header.jsp" %>

	<div class="container" id="contObligationFileTransfer">		
		<div class="xform" style="display:none" id="frmSearch">
			<header>Obligation File Transfers</header>

			<fieldset>
				<div class="row">
					<div class="col-sm-2"><section><label for="date" class="label">Date:</label></section></div>
					<div class="col-sm-2">
						<section class="input">
						<i class="icon-append fa fa-clock-o"></i>
						<input type="text" id="date" placeholder="Date" data-role="datetimepicker">
						<b class="tooltip tooltip-top-right"></b></section>
					</div>
					<div class="col-sm-2"><section><label for="fileName" class="label">Transacting Entity:</label></section></div>
					<div class="col-sm-2">
						<section class="input">
						<input type="text" id="fileName" placeholder="Transacting Entity">
						<b class="tooltip tooltip-top-right"></b></section>
					</div>
					<div class="col-sm-2"><section><label for="fileType" class="label">File Type:</label></section></div>
					<div class="col-sm-2">
						<section class="select">
						<select id="fileType"><option value="">Select File Type</option></select>
						<b class="tooltip tooltip-top-right"></b><i></i></section>
					</div>
				</div>
				<div class="row">
					<div class="col-sm-2"><section><label for="facilitator" class="label">Facilitator:</label></section></div>
					<div class="col-sm-2">
						<section class="select">
						<select id="facilitator"><option value="">Select Facilitator</option></select>
						<b class="tooltip tooltip-top-right"></b><i></i></section>
					</div>
					<div class="col-sm-2"><section><label for="recordCount" class="label">No of Records:</label></section></div>
					<div class="col-sm-2">
						<section class="input">
						<input type="text" id="recordCount" placeholder="No of Records">
						<b class="tooltip tooltip-top-right"></b></section>
					</div>
					<div class="col-sm-2"><section><label for="totalValue" class="label">Total Value:</label></section></div>
					<div class="col-sm-2">
						<section class="input">
						<input type="text" id="totalValue" placeholder="Total Value">
						<b class="tooltip tooltip-top-right"></b></section>
					</div>
				</div>
				<div class="row">
					<div class="col-sm-2"><section><label for="generatedByAuId" class="label">Generated By:</label></section></div>
					<div class="col-sm-2">
						<section class="input">
						<input type="text" id="generatedByAuId" placeholder="Generated By">
						<b class="tooltip tooltip-top-right"></b></section>
					</div>
					<div class="col-sm-2"><section><label for="generatedTime" class="label">Generated Time:</label></section></div>
					<div class="col-sm-2">
						<section class="input">
						<i class="icon-append fa fa-clock-o"></i>
						<input type="text" id="generatedTime" placeholder="Generated Time" data-role="datetimepicker">
						<b class="tooltip tooltip-top-right"></b></section>
					</div>
					<div class="col-sm-2"><section><label for="status" class="label">Status:</label></section></div>
					<div class="col-sm-2">
						<section class="select">
						<select id="status"><option value="">Select Status</option></select>
						<b class="tooltip tooltip-top-right"></b><i></i></section>
					</div>
				</div>
				<div class="row">
					<div class="col-sm-2"><section><label for="returnUploadedByAuId" class="label">Return file uploaded by:</label></section></div>
					<div class="col-sm-2">
						<section class="input">
						<input type="text" id="returnUploadedByAuId" placeholder="Return file uploaded by">
						<b class="tooltip tooltip-top-right"></b></section>
					</div>
					<div class="col-sm-2"><section><label for="returnUploadedTime" class="label">Return upload time:</label></section></div>
					<div class="col-sm-2">
						<section class="input">
						<i class="icon-append fa fa-clock-o"></i>
						<input type="text" id="returnUploadedTime" placeholder="Return upload time" data-role="datetimepicker">
						<b class="tooltip tooltip-top-right"></b></section>
					</div>
				</div>
			</fieldset>
			<fieldset>
				<div class="row">
					<div class="col-sm-12">
						<div class="btn-groupX">
							<button type="button" class="btn btn-primary" id=btnSearch><span class="fa fa-search"></span> Search</button>
							<button type="button" class="btn btn-default" id=btnNew><span class="fa fa-plus"></span> New</button>
							<button type="button" class="btn btn-default" id=btnModify><span class="fa fa-pencil"></span> Modify</button>
							<button type="button" class="btn btn-default" id=btnView><span class="fa fa-eye"></span> View</button>
							<button type="button" class="btn btn-default" id=btnRemove><span class="fa fa-minus"></span> Remove</button>
						</div>
					</div>
				</div>
			</fieldset>
			<div class="tab-pane panel panel-default">
				<fieldset>
					<div class="row">
						<div class="col-sm-12">
							<table class="table table-striped table-bordered table-condensed" id="tblData" width="1100px">
								<thead><tr>
									<th data-visible="false" data-name="id">Id</th>
									<th data-width="100px" data-name="date">Date</th>
									<th data-width="100px" data-name="fileName">Transacting Entity</th>
									<th data-width="100px" data-name="fileType">File Type</th>
									<th data-width="100px" data-name="facilitator">Facilitator</th>
									<th data-width="100px" data-name="recordCount">No of Records</th>
									<th data-width="100px" data-name="totalValue">Total Value</th>
									<th data-width="100px" data-name="generatedByAuId">Generated By</th>
									<th data-width="100px" data-name="generatedTime">Generated Time</th>
									<th data-width="100px" data-name="status">Status</th>
									<th data-width="100px" data-name="returnUploadedByAuId">Return file uploaded by</th>
									<th data-width="100px" data-name="returnUploadedTime">Return upload time</th>
								</tr></thead>
							</table>
						</div>
					</div>
				</fieldset>
			</div>
		</div>
		
		<div class="xform" style="display:none" id="frmMain">
			<header>Obligation File Transfers</header>

			<fieldset>
				<div class="row">
					<div class="col-sm-2"><section><label for="date" class="label">Date:</label></section></div>
					<div class="col-sm-4">
						<section class="input">
						<i class="icon-append fa fa-clock-o"></i>
						<input type="text" id="date" placeholder="Date" data-role="datetimepicker">
						<b class="tooltip tooltip-top-right"></b></section>
						<section class="view"></section>
					</div>
					<div class="col-sm-2"><section><label for="fileName" class="label">Transacting Entity:</label></section></div>
					<div class="col-sm-4">
						<section class="input">
						<input type="text" id="fileName" placeholder="Transacting Entity">
						<b class="tooltip tooltip-top-right"></b></section>
						<section class="view"></section>
					</div>
				</div>
				<div class="row">
					<div class="col-sm-2"><section><label for="fileType" class="label">File Type:</label></section></div>
					<div class="col-sm-4">
						<section class="select">
						<select id="fileType"><option value="">Select File Type</option></select>
						<b class="tooltip tooltip-top-right"></b><i></i></section>
						<section class="view"></section>
					</div>
					<div class="col-sm-2"><section><label for="facilitator" class="label">Facilitator:</label></section></div>
					<div class="col-sm-4">
						<section class="select">
						<select id="facilitator"><option value="">Select Facilitator</option></select>
						<b class="tooltip tooltip-top-right"></b><i></i></section>
						<section class="view"></section>
					</div>
				</div>
				<div class="row">
					<div class="col-sm-2"><section><label for="recordCount" class="label">No of Records:</label></section></div>
					<div class="col-sm-4">
						<section class="input">
						<input type="text" id="recordCount" placeholder="No of Records">
						<b class="tooltip tooltip-top-right"></b></section>
						<section class="view"></section>
					</div>
					<div class="col-sm-2"><section><label for="totalValue" class="label">Total Value:</label></section></div>
					<div class="col-sm-4">
						<section class="input">
						<input type="text" id="totalValue" placeholder="Total Value">
						<b class="tooltip tooltip-top-right"></b></section>
						<section class="view"></section>
					</div>
				</div>
				<div class="row">
					<div class="col-sm-2"><section><label for="generatedByAuId" class="label">Generated By:</label></section></div>
					<div class="col-sm-4">
						<section class="input">
						<input type="text" id="generatedByAuId" placeholder="Generated By">
						<b class="tooltip tooltip-top-right"></b></section>
						<section class="view"></section>
					</div>
					<div class="col-sm-2"><section><label for="generatedTime" class="label">Generated Time:</label></section></div>
					<div class="col-sm-4">
						<section class="input">
						<i class="icon-append fa fa-clock-o"></i>
						<input type="text" id="generatedTime" placeholder="Generated Time" data-role="datetimepicker">
						<b class="tooltip tooltip-top-right"></b></section>
						<section class="view"></section>
					</div>
				</div>
				<div class="row">
					<div class="col-sm-2"><section><label for="status" class="label">Status:</label></section></div>
					<div class="col-sm-4">
						<section class="select">
						<select id="status"><option value="">Select Status</option></select>
						<b class="tooltip tooltip-top-right"></b><i></i></section>
						<section class="view"></section>
					</div>
					<div class="col-sm-2"><section><label for="returnUploadedByAuId" class="label">Return file uploaded by:</label></section></div>
					<div class="col-sm-4">
						<section class="input">
						<input type="text" id="returnUploadedByAuId" placeholder="Return file uploaded by">
						<b class="tooltip tooltip-top-right"></b></section>
						<section class="view"></section>
					</div>
				</div>
				<div class="row">
					<div class="col-sm-2"><section><label for="returnUploadedTime" class="label">Return upload time:</label></section></div>
					<div class="col-sm-4">
						<section class="input">
						<i class="icon-append fa fa-clock-o"></i>
						<input type="text" id="returnUploadedTime" placeholder="Return upload time" data-role="datetimepicker">
						<b class="tooltip tooltip-top-right"></b></section>
						<section class="view"></section>
					</div>
				</div>
			</fieldset>
			<footer>
				<div class="btn-groupX">
					<button type="button" class="btn btn-primary" id=btnSave><span class="fa fa-save"></span> Save</button>
					<button type="button" class="btn btn-primary" id=btnEdit><span class="fa fa-pencil"></span> Edit</button>
					<button type="button" class="btn btn-close" id=btnClose><span class="fa fa-close"></span> Close</button>
				</div>
			</footer>
		</div>
	</div>

    <script src="../js/jquery-3.4.1.min.js"></script>
	<script src="../js/jquery-migrate-3.0.1.min.js"></script>
    <script src="../js/bootstrap.js"></script>
	<script src="../js/jquery.xform.js"></script>
	<script src="../js/app.js"></script>

	<!-- <script src="../js/bootstrap-datetimepicker.js"></script> -->
	<!-- <script src="../js/jquery.bootstrap-duallistbox.js"></script> -->
	<!-- <script src="../js/bootstrap-multiselect.js"></script> -->
	<!-- <script src="../js/select2.js"></script> -->
	<!-- <script src="../js/bootstrap-slider.js"></script> -->
	<!-- <script src="../js/datatables.js"></script> -->

	<script type="text/javascript">
		var crudObligationFileTransfer$ = null;
		$(document).ready(function() {
			var lFormConfig = null;
			var lConfig = {
					resource: "obligfiletrnf",
					autoRefresh: true,
<%
if (lNewBool) {
%>					new: true,
<%
} else if (lModify != null) {
%>					modify: <%=lModify%>,
<%
}
%>			};
			lConfig = $.extend(lConfig, lFormConfig);
			crudObligationFileTransfer$ = $('#contObligationFileTransfer').xcrudwrapper(lConfig);
		});
		
	</script>
<%@ include file="footer1.jsp" %>

</body>
</html>