<%@page import="com.xlx.treds.TredsHelper"%>
<%@page import="com.xlx.common.utilities.CommonUtilities"%>
<%@page import="java.math.BigDecimal"%>
<%@page import="java.text.DecimalFormat"%>
<%@page import="java.util.List"%>
<%@page import="java.util.Map"%>
<%@page import="java.text.SimpleDateFormat"%>
<%@page import="com.xlx.commonn.BeanMetaFactory"%>
<%@page import="com.xlx.commonn.CommonAppConstants"%>
<%@page import="com.xlx.common.utilities.FormatHelper"%>
<%@page import="java.sql.Date"%>
<%@page import="org.apache.commons.lang.StringEscapeUtils"%>
<%@page import="java.util.HashMap"%>
<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
    pageEncoding="ISO-8859-1"%>
<%!
public String formatData(Object pData)
{
	try
	{
		if(pData != null)
			return StringEscapeUtils.escapeXml(pData.toString());
	}
	catch(Exception lEx)
	{
		
	}
	return "";
}
%>
<%
SimpleDateFormat lDateTimeFormatter = BeanMetaFactory.getInstance().getDateTimeFormatter();
String lContextPath=request.getContextPath();
Map<String, Object> lData = (Map<String, Object>) request.getAttribute("data");
%>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1"></meta>
<title>Payment Advise</title>
<style type="text/css">
div.header {
    display: block; text-align: center; 
    position: running(header);
}
div.footer {
    display: block; text-align: center;
    position: running(footer);
}
div.content {page-break-after: always;}
h2 {
	color: #298FCE;
	font-family:Arial;
	font-size: 24px;
}
.mytable {
    border-collapse: collapse;
}

.mytable th{
    border: 1px solid black;
}
.mytable td {
    border: 1px solid black;
}

body
{
	font-family:Arial;
	font-size: 12.5px;
}

@page { 
	 /*size: 8.50in 9.50in;*//* width height */
	 size: A4;   /* auto is the initial value */
	 margin-top: 15%;
	 margin-left:5%;
	 margin-right:5%;
	 padding: 0px;
	 
	 border: 0pt solid black;
	 
	 @top-right {
        content: element(header); 
        vertical-align: bottom;
        padding-bottom: 10px;
    }
	@bottom-left {
	    content: element(footer);
	}
	@bottom-right {
	    font-style: italic; 
	    font-size:11px;
	    color:black;
	    content: counter(page);
	 text-align:center;
	}
	@top-center {
	  content: element(current);
	  text-align:center;
	}
}
@media print
{
	.pagebreak { height:0; page-break-before:always; margin:0; border-top:none; }
}
@media screen{
    .pagebreak  { height:10px; border-top:0px dotted #999; margin-bottom:13px; }
}

div.indent{ padding-left: 1.8em }

</style>
</head>
<body>
<div class='header'>
<center>
<table border="0" cellspacing="10" cellpadding="0">
	<tr>
		<td style='text-align:left' width="20%"><img src="<%=TredsHelper.getInstance().getApplicationURL()%>../images/logo2x.png" width="108px" height="36px" border="0px" /></td>
		<td><h2>RECEIVABLES EXCHANGE OF INDIA LIMITED</h2></td>
	</tr>
</table>
</center>
</div>

<div style="margin:100px;">
		<table class="mytable" colspan="2" width="100%">
			<tr>
				<th> Instrument number - Autogenerated by RXIL</th>
     		   <td> <%=formatData(lData.get("inId"))%> </td>
			</tr>
			<tr>
		        <th> Factoring Unit Id - Autogenerated by RXIL </th>
		        <td> <%=formatData(lData.get("fuId"))%> </td>
		    </tr>
<%if(Boolean.TRUE.equals(lData.get("isPurchaser"))){
%>
		    <tr>
				<th> Invoice no </th>
		        <td> <%=formatData(lData.get("instNumber"))%> </td>
		    </tr>
		    <tr>
				<th> Invoice Date </th>
		        <td> <%=formatData(lData.get("instDate"))%> </td>
		    </tr>
		    <tr>
				<th> Goods Acceptance Date </th>
		        <td> <%=formatData(lData.get("goodsAcceptDate"))%> </td>
		    </tr>
		    <tr>
				<th> Statutory Due Date </th>
		        <td> <%=formatData(lData.get("statDueDate"))%> </td>
		    </tr>
<%
}
%>
		    <tr>
				<th> Instrument Count </th>
				<td> <%=formatData(lData.get("instCount"))%> </td>
			</tr>
<%if(Boolean.TRUE.equals(lData.get("isPurchaser"))){
%>
		    <tr>
				<th> Purchase Order Number</th>
		        <td> <%=formatData(lData.get("poNumber"))%> </td>
			</tr>
<%
}
%>
			<tr>
		        <th> Invoice Amount </th>
		        <td> <%=formatData(lData.get("amount"))%> </td>
		    </tr>
		    <tr>
				<th> Deductions </th>
		        <td> <%=formatData(lData.get("deductions"))%> </td>
		    </tr>
		    <tr>
				<th> TDS </th>
		        <td> <%=formatData(lData.get("tds"))%> </td>
		    </tr>
		    <tr>
				<th> Factoring Unit value </th>
		        <td> <%=formatData(lData.get("factUnitValue"))%> </td>
		    </tr>
		    <tr>
				<th> Financed %  </th>
		        <td> <%=formatData(lData.get("financedPer"))%> </td>
		    </tr>
		    <tr>
				<th> Financed Amount </th>
				<td> <%=formatData(lData.get("financedAmount"))%> </td>
			</tr>
		    <tr>	
		        <th>Discounting Rate</th>
		        <td><%=formatData(lData.get("discountingRate"))%></td>
		    </tr>
		    <tr>
		        <th>Buyer Name</th>
		        <td><%=formatData(lData.get("buyerName"))%></td>
		    </tr>
		    <tr>
		        <th>Buyer Code</th>
		        <td><%=formatData(lData.get("buyerCode"))%></td>
		    </tr>
		    <tr>
		        <th>Buyer Ref Code</th>
		        <td><%=formatData(lData.get("buyerRefCode"))%></td>
		    </tr>
		    <tr>
		        <th>Buyer Location</th>
		        <td><%=formatData(lData.get("buyerLocation"))%></td>
		    </tr>
		    <tr>
		        <th>Seller Name</th>
		        <td><%=formatData(lData.get("sellerName"))%></td>
		    </tr>
		    <tr>
		        <th>Seller Code</th>
		        <td><%=formatData(lData.get("sellerCode"))%></td>
		    </tr>
		    <tr>
		        <th>Seller Ref Code</th>
		        <td><%=formatData(lData.get("sellerRefCode"))%></td>
		    </tr>
		    <tr>
		        <th>Seller Location</th>
		        <td><%=formatData(lData.get("sellerLocation"))%></td>
		    </tr>
		    <tr>
		        <th>MSME Category</th>
		        <td><%=formatData(lData.get("msmeCategory"))%></td>
		    </tr>
		    <tr>
		        <th>Financier Name</th>
		        <td><%=formatData(lData.get("financierName"))%></td>
		    </tr>
		    <tr>
		        <th>Financier Code</th>
		        <td><%=formatData(lData.get("financierCode"))%></td>
		    </tr>
		    <tr>
		        <th>Financier Location</th>
		        <td><%=formatData(lData.get("financierLocation"))%></td>
		    </tr>
		    <tr>
		        <th>Bid Acceptance Date and Time</th>
		        <td><%=formatData(lData.get("bidAcceptanceDateTime"))%></td>
		    </tr>
		    <tr>
		        <th>Financing Date (Debit Date)</th>
		        <td><%=formatData(lData.get("financingDebitDate"))%></td>
		    </tr>
		    <tr>
		        <th>Due Date (Leg 2)</th>
		        <td><%=formatData(lData.get("dueDateLeg2"))%></td>
		    </tr>
		    <tr>
		        <th>Tenor</th>
		        <td><%=formatData(lData.get("tenor"))%></td>
		    </tr>
<%if(Boolean.TRUE.equals(lData.get("isPurchaser"))){
%>	
			  <tr>
		        <th>Interest Collection (leg 1 / leg 2)</th>
		        <td><%=formatData(lData.get("intColLeg1Leg2"))%></td>
		    </tr>
<!-- 		    <tr> -->
<!-- 		        <th>Interest Cost Bearer (Seller / Buyer / Splite)</th> -->
<%-- 		        <td><%=formatData(lData.get("intCostBearer"))%></td> --%>
<!-- 		    </tr> -->
<%
}
%>
		    <tr>
		        <th>Interest Amount (on Leg 1)</th>
		        <td><%=formatData(lData.get("intAmountLeg1"))%></td>
		    </tr>
		    <tr>
		        <th>Platform Charge bearer</th>
		        <td><%=formatData(lData.get("platformChargeBearer"))%></td>
		    </tr>
		    <tr>
		        <th>RXIL Charges (in Rs)</th>
		        <td><%=formatData(lData.get("rxilChargesAmount"))%></td>
		    </tr>
		    <tr>
		        <th>GST (@ 18%)</th>
		        <td><%=formatData(lData.get("gstAmount"))%></td>
		    </tr>
		    <tr>
		        <th>Total Deduction (for Seller if seller is bearing the cost)</th>
		        <td><%=formatData(lData.get("totalDeduction"))%></td>
		    </tr>
		    <tr>
		        <th>Amount Credit to Seller (After deducting Seller cost bearing portion)</th>
		        <td><%=formatData(lData.get("amountCreditToseller"))%></td>
		    </tr>
<%if(Boolean.TRUE.equals(lData.get("isPurchaser"))){
%>	
		    <tr>
		        <th>Buyer Cost </th>
		        <td><%=formatData(lData.get("buyerCost"))%></td>
		    </tr>
<%
}
%>
		    <tr>
		        <th>Debit to Financier </th>
		        <td><%=formatData(lData.get("debitToFinancier"))%></td>
		    </tr>
<%if(Boolean.TRUE.equals(lData.get("isPurchaser"))){
%>
		    <tr>
		        <th>Interest on Leg 2 (if buyer is bearing the cost and collection of interest at leg 2)</th>
		        <td><%=formatData(lData.get("intOnLeg2"))%></td>
		    </tr>
		    <tr>
		        <th>Leg 2 Amount  </th>
		        <td><%=formatData(lData.get("leg2Amount"))%></td>
		    </tr>
<%
}
%>
		    <tr>
		        <th>Transaction Status</th>
		        <td><%=formatData(lData.get("transactionStatus"))%></td>
		    </tr>
<%if(Boolean.TRUE.equals(lData.get("isPurchaser"))){
%>
			<tr>
		        <th>Extended Bid Rate</th>
		        <td><%=formatData(lData.get("extendedBidRate"))%></td>
		    </tr>
		    <tr>
		        <th>Extended Due Date</th>
		        <td><%=formatData(lData.get("extendedDueDate"))%></td>
		    </tr>
		    <tr>
		        <th>Interest Amount (Extension)</th>
		        <td><%=formatData(lData.get("interestExtAmount"))%></td>
		    </tr>
		    <tr>
		        <th>Extended Platform Charges</th>
		        <td><%=formatData(lData.get("extendedPlatformCharges"))%></td>
		    </tr>
		    <tr>
		        <th>Extended Platform Charge GST</th>
		        <td><%=formatData(lData.get("extendedPlatformChargesGst"))%></td>
		    </tr>
		    <tr>
		        <th>Extended Tenor</th>
		        <td><%=formatData(lData.get("extendedTenor"))%></td>
		    </tr>
		    <tr>
		        <th>Leg 2 Amount (Extended request)</th>
		        <td><%=formatData(lData.get("leg2Amount"))%></td>
		    </tr>
<%
}
%>
		</table>
		<br/>
		

</div>

<div>
<br/><br/>
<p><b>Notes:</b></p>

<p>Factoring unit Value = Invoice amount - TDS - Deductions</p>

<p>Financed Amount = Factoring unit Value * Finance %</p>

<p>Tenor date = Financing Date (Debit Date) - Due Date</p>

<p>Interest Amount (on Leg1) = Financed Amount * (Discounting rate/100) * (Tenor/365)</p>

<p>RXIL Charges = Financed Amount * RXIL Charge % * (Tenor/365)</p>

<p>Total Deduction = Interest Amount + RXIL Charges + GST</p>

<p>Amount Credited to Seller = Financed Amount - Total Deduction</p>

<p>Debit to Financier = Financed Amount - Interest Amount</p>

<p>Leg 2 Amount = Financed Amount + Interest on Leg2</p>

</div>

<div class='footer'>
<center>
This is a computer generated letter and does not require any signature.
</center>
</div>

</body>

</html>